# This file was generated by GoReleaser. DO NOT EDIT.
cask "es" do
  name "es"
  desc ""
  homepage ""
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "es"

  on_macos do
    on_intel do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_darwin_amd64.tar.gz"
      sha256 "00cec56d269ba7a2575b1c46f667cbce275ccb1b2a6470737253501212ac4c94"
    end
    on_arm do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_darwin_arm64.tar.gz"
      sha256 "17944c0e57c4a8ec2d4d6e453ee97ba0f2661d70e115eb4f108370f1433bd7b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_linux_amd64.tar.gz"
      sha256 "f018d8c98da414d71c7ef0c17311d8cf51b546bac5c0707e005f1157b66df5af"
    end
    on_arm do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_linux_arm64.tar.gz"
      sha256 "5a2fb40b29f4a6c4f870d415b0b36fdd7c0c4bff8a3e5a123672b9113d4a6c2f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/es"]
    end
  end

  # No zap stanza required
end
