# This file was generated by GoReleaser. DO NOT EDIT.
cask "es" do
  name "es"
  desc ""
  homepage ""
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "es"

  on_macos do
    on_intel do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_darwin_amd64.tar.gz"
      sha256 "517bd03d8b9442cc82a0220c8b939f57db214235f73f025b232b7dc401af93c5"
    end
    on_arm do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_darwin_arm64.tar.gz"
      sha256 "b92320c845c795c6da9ba527aff32d1b06824e7c722537d4b4f1811a5415d104"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_linux_amd64.tar.gz"
      sha256 "79998c3021e9fb5b0953819a1f900fe45db302282bdc2987e665d4e4aa59559b"
    end
    on_arm do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_linux_arm64.tar.gz"
      sha256 "7cd28855be461d46015ee22ec5935369bbe6530ea2c1ddda5c58e05a53e3f05e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/es"]
    end
  end

  # No zap stanza required
end
